baseurl: baseURL
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: 费益洲的博客

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
  post: /p/:slug/
  page: /:slug/

params:
  moreMeta: true

  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon:  # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

  footer:
    since: 2023
#    customText: <a href="https://beian.miit.gov.cn/" target="_blank">备案号</a>
#      <a href="https://beian.miit.gov.cn/" target="_blank">粤ICP备2022030313号-1</a>

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    emoji: 🤔
    subtitle: Talk is cheep, show me the code.
    avatar:
      enabled: true
      local: true
      src: img/avatar.jpg

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: true
    provider: gitalk

    gitalk:
      owner: your githubID
      admin: your githubID
      repo: github repo
      clientID: clientID
      clientSecret: secret
      labels: "gitalk"
      perPage: 15
      pagerDirection: "last"
      createIssueManually: false
      distractionFreeMode: false
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # Your Twitter username
      site:

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  main: [ ]

  social:
    - identifier: github
      name: GitHub
      url: https://github.com/feiyizhou
      params:
        icon: brand-github
    - identifier: bilibili
      name: bilibili
      url: https://space.bilibili.com/446220767
      params:
        icon: brand-bilibili

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
